import Head from 'next/head'
import Header from '@/components/Header';
import About from '@/components/About';
import Education from '@/components/Education';
import Experience from '@/components/Experience';
import Projects from '@/components/Projects';
import Contact from '@/components/Contact';
import { useEffect, useRef, useState } from 'react';

export default function Home() {
  const ref = useRef<HTMLDivElement>(null);
  const [toggle, setToggle] = useState(null);

  useEffect(() => {
    ref?.current?.scrollIntoView({ behavior: 'smooth', block: 'start'})
  },[toggle])
  
  return (
    <>
      <Head>
        <title>Rakesh Ch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header setToggle={setToggle} />
      <About scrollRef={ toggle === 'About' ? ref : null} />
      <Education scrollRef={ toggle === 'Education' ? ref : null} />
      <Experience scrollRef={ toggle === 'Experience' ? ref : null} />
      <Projects  scrollRef={ toggle === 'Projects' ? ref : null}/>
      <Contact scrollRef={ toggle === 'Contact' ? ref : null} />
    </>
  )
}
